[Core]
  IP = "0.0.0.0"
  RPCPort = "30159"
  GRPCPort = "30190"


[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip4/127.0.0.1/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  MutualPeers = []
  PeerExchange = false
  RoutingTableRefreshPeriod = "1m0s"
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = "1m0s"

[RPC]
  Address = "0.0.0.0"
  Port = "26658"

[Gateway]
  Address = "0.0.0.0"
  Port = "26659"
  Enabled = false

[Share]
  PeersLimit = 5
  DiscoveryInterval = "30s"
  AdvertiseInterval = "30s"
  UseShareExchange = true
  [Share.ShrExEDSParams]
    ServerReadTimeout = "5s"
    ServerWriteTimeout = "1m0s"
    HandleRequestTimeout = "1m0s"
    ConcurrencyLimit = 10
    BufferSize = 32768
  [Share.ShrExNDParams]
    ServerReadTimeout = "5s"
    ServerWriteTimeout = "1m0s"
    HandleRequestTimeout = "1m0s"
    ConcurrencyLimit = 10

[Header]
  TrustedHash = ""
  TrustedPeers = []
  [Header.Store]
    StoreCacheSize = 4096
    IndexCacheSize = 16384
    WriteBatchSize = 2048
  [Header.Syncer]
    TrustingPeriod = "168h0m0s"
  [Header.Server]
    WriteDeadline = "8s"
    ReadDeadline = "1m0s"
    RangeRequestTimeout = "10s"
  [Header.Client]
    MaxHeadersPerRangeRequest = 64
    RangeRequestTimeout = "8s"
    TrustedPeersRequestTimeout = "300ms"

[DASer]
  SamplingRange = 100
  ConcurrencyLimit = 16
  BackgroundStoreInterval = "10m0s"
  SampleFrom = 1
  SampleTimeout = "4m0s"


[State]
  KeyringAccName = "kvintnode"
  KeyringBackend = "test"

